spring:
  messages:
    basename: "i18n/appmessages"
    encoding: "UTF-8"
  output:
    ansi:
      enabled: ALWAYS

testing:
  locale: ru_RU
  dao:
    resource-basename: "questions"
    encoding: "UTF-8"
  service:
    theme: "Java testing from CSV"
    passing-score: 40