---
apiVersion: v1
kind: Service
metadata:
  name: library-db-oshoev-service
spec:
  type: NodePort
  selector:
    app: library-db-oshoev
  ports:
    - name: "postgres"
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30432