---
apiVersion: v1
kind: Service
metadata:
  name: library-web-oshoev-service
spec:
  type: NodePort
  selector:
    app: library-web-oshoev
  ports:
    - name: "http"
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080